Repository PrismLibrary/Prism, pull requests merged in 2018-06, with the labels that each got.

#1431 XAML Navigation Extensions
  Source/Xamarin/Prism.DI.Forms.Tests/Fixtures/PrismApplicationFixture.cs
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/PrismApplicationMock.cs
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/ViewModels/XamlViewMockAViewModel.cs
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/ViewModels/XamlViewMockBViewModel.cs
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMockA.xaml
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMockA.xaml.cs
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMockB.xaml
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/Views/XamlViewMockB.xaml.cs
  Source/Xamarin/Prism.Forms/Navigation/KnownNavigationParameters.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/GoBackExtension.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/GoBackType.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigateToExtension.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/Navigation.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationExtensionBase.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameter.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameterExtensions.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameters.cs
  Source/Xamarin/Prism.Forms/Prism.Forms.csproj
Labels: XF, enhancement

#1469 Make Xamarin.Forms DependencyResolver Opt-In
  Source/Directory.Build.props
  Source/Prism.Tests/Prism.Tests.csproj
  Source/Prism/Prism.csproj
  Source/Windows10/Prism.Autofac.Windows/Prism.Autofac.Windows.csproj
  Source/Windows10/Prism.SimpleInjector.Windows/Prism.SimpleInjector.Windows.csproj
  Source/Windows10/Prism.Unity.Windows/Prism.Unity.Windows.csproj
  Source/Windows10/Prism.Windows.Tests/Prism.Windows.Tests.csproj
  Source/Windows10/Prism.Windows/Prism.Windows.csproj
  Source/Wpf/Prism.Autofac.Wpf.Tests/Prism.Autofac.Wpf.Tests.csproj
  Source/Wpf/Prism.Autofac.Wpf.Tests/packages.config
  Source/Wpf/Prism.Autofac.Wpf/Prism.Autofac.Wpf.csproj
  Source/Wpf/Prism.Autofac.Wpf/packages.config
  Source/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj
  Source/Wpf/Prism.DryIoc.Wpf.Tests/packages.config
  Source/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
  Source/Wpf/Prism.DryIoc.Wpf/packages.config
  Source/Wpf/Prism.Ninject.Wpf.Tests/Prism.Ninject.Wpf.Tests.csproj
  Source/Wpf/Prism.Ninject.Wpf.Tests/packages.config
  Source/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj
  Source/Wpf/Prism.Unity.Wpf.Tests/packages.config
  Source/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj
  Source/Wpf/Prism.Unity.Wpf/packages.config
  Source/Xamarin/Prism.Autofac.Forms.Tests/Prism.Autofac.Forms.Tests.csproj
  Source/Xamarin/Prism.Autofac.Forms/Prism.Autofac.Forms.csproj
  Source/Xamarin/Prism.Autofac.Forms/PrismApplication.cs
  Source/Xamarin/Prism.DI.Forms.Tests/Mocks/PrismApplicationMock.cs
  Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
  Source/Xamarin/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
  Source/Xamarin/Prism.DryIoc.Forms/PrismApplication.cs
  Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
  Source/Xamarin/Prism.Forms/Prism.Forms.csproj
  Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
  Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
  Source/Xamarin/Prism.Unity.Forms/Prism.Unity.Forms.csproj
  Source/Xamarin/Prism.Unity.Forms/PrismApplication.cs
  Source/build/Prism.Autofac.Wpf.nuspec
  Source/build/Prism.DryIoc.Wpf.nuspec
  Source/build/Prism.Unity.Wpf.nuspec
  Source/global.json
Labels: XF

#1476 Module Alignment
  Source/Prism/Common/ListDictionary.cs
  Source/Prism/Modularity/CyclicDependencyFoundException.Desktop.cs
  Source/Prism/Modularity/CyclicDependencyFoundException.cs
  Source/Prism/Modularity/DuplicateModuleException.Desktop.cs
  Source/Prism/Modularity/DuplicateModuleException.cs
  Source/Prism/Modularity/IModuleCatalogItem.cs
  Source/Prism/Modularity/IModuleInitializer.cs
  Source/Prism/Modularity/IModuleManager.cs
  Source/Prism/Modularity/LoadModuleCompletedEventArgs.cs
  Source/Prism/Modularity/ModularityException.Desktop.cs
  Source/Prism/Modularity/ModularityException.cs
  Source/Prism/Modularity/ModuleDownloadProgressChangedEventArgs.cs
  Source/Prism/Modularity/ModuleInfo.Desktop.cs
  Source/Prism/Modularity/ModuleInfo.cs
  Source/Prism/Modularity/ModuleInitializeException.Desktop.cs
  Source/Prism/Modularity/ModuleInitializeException.cs
  Source/Prism/Modularity/ModuleNotFoundException.Desktop.cs
  Source/Prism/Modularity/ModuleNotFoundException.cs
  Source/Prism/Modularity/ModuleTypeLoaderNotFoundException.Desktop.cs
  Source/Prism/Modularity/ModuleTypeLoaderNotFoundException.cs
  Source/Prism/Modularity/ModuleTypeLoadingException.Desktop.cs
  Source/Prism/Modularity/ModuleTypeLoadingException.cs
  Source/Prism/Prism.csproj
  Source/Prism/Properties/Resources.Designer.cs
  Source/Prism/Properties/Resources.resx
  Source/Wpf/Prism.Wpf.Tests/Modularity/ModuleCatalogXaml/SimpleModuleCatalog.xaml
  Source/Wpf/Prism.Wpf/Properties/Resources.Designer.cs
  Source/Wpf/Prism.Wpf/Properties/Resources.resx
  Source/Xamarin/Prism.Forms/Modularity/IModuleCatalogExtensions.cs
  Source/Xamarin/Prism.Forms/Modularity/IModuleInitializer.cs
  Source/Xamarin/Prism.Forms/Modularity/IModuleManager.cs
  Source/Xamarin/Prism.Forms/Modularity/ModuleCatalog.cs
  Source/Xamarin/Prism.Forms/Modularity/ModuleInfo.cs
  Source/Xamarin/Prism.Forms/Modularity/ModuleInitializer.cs
  Source/Xamarin/Prism.Forms/Modularity/ModuleManager.cs
Labels: WPF, XF
