Repository PrismLibrary/Prism, pull requests merged in 2019-06, with the labels that each got.

#1826 Using Enum for IDialogResult.Result
  Sandbox/Wpf/HelloWorld/HelloWorld/Dialogs/DialogViewModelBase.cs
  Sandbox/Wpf/HelloWorld/HelloWorld/ViewModels/MainWindowViewModel.cs
  Source/Wpf/Prism.Wpf/Services/Dialogs/ButtonResult.cs
  Source/Wpf/Prism.Wpf/Services/Dialogs/DialogParameters.cs
  Source/Wpf/Prism.Wpf/Services/Dialogs/DialogResult.cs
  Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogAware.cs
  Source/Wpf/Prism.Wpf/Services/Dialogs/IDialogResult.cs
  Source/build/azure-pipelines.yml
Labels: WPF

#1827 Fully support bindings for Xaml Navigation
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MyMasterDetailViewModel.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml
  Sandbox/Xamarin/HelloWorld/ModuleA/ViewModels/ViewAViewModel.cs
  Sandbox/Xamarin/HelloWorld/ModuleA/Views/ViewA.xaml
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationExtensionBase.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameterExtensions.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameters.cs
Labels: XF, bug

#1825 adding DialogService
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.UWP/HelloWorld.UWP.csproj
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld.iOS/HelloWorld.iOS.csproj
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/App.xaml.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/HelloWorld.csproj
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Strings/Resources.Designer.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Strings/Resources.resx
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/DemoDialogViewModel.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/DialogDemoPageViewModel.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/MainPageViewModel.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/SomeOtherViewModel.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/UserAlertViewModel.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/ViewModels/ViewModelBase.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/DemoDialog.xaml
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/DemoDialog.xaml.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/DialogDemoPage.xaml
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/DialogDemoPage.xaml.cs
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/MyMasterDetail.xaml
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/UserAlert.xaml
  Sandbox/Xamarin/HelloWorld/HelloWorld/HelloWorld/Views/UserAlert.xaml.cs
  Sandbox/Xamarin/HelloWorld/ModuleA/ModuleA.csproj
  Source/Prism/Common/ParametersBase.cs
  Source/Prism/Common/ParametersExtensions.cs
  Source/Xamarin/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
  Source/Xamarin/Prism.Forms.Tests/Prism.Forms.Tests.csproj
  Source/Xamarin/Prism.Forms/AppModel/AutoInitializeAttribute.cs
  Source/Xamarin/Prism.Forms/AppModel/IAutoInitialize.cs
  Source/Xamarin/Prism.Forms/Common/PageUtilities.cs
  Source/Xamarin/Prism.Forms/Common/UriParsingHelper.cs
  Source/Xamarin/Prism.Forms/Ioc/IContainerRegistryExtensions.cs
  Source/Xamarin/Prism.Forms/Navigation/NavigationParameterAttribute.cs
  Source/Xamarin/Prism.Forms/Navigation/NavigationParameters.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationExtensionBase.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameter.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameterExtensions.cs
  Source/Xamarin/Prism.Forms/Navigation/Xaml/NavigationParameters.cs
  Source/Xamarin/Prism.Forms/Prism.Forms.csproj
  Source/Xamarin/Prism.Forms/PrismApplicationBase.cs
  Source/Xamarin/Prism.Forms/Properties/AssemblyInfo.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/DialogContainer.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/DialogException.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/DialogParameters.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/DialogResult.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/DialogService.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/IDialogAware.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/IDialogParameters.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/IDialogResult.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/IDialogService.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/IDialogServiceExtensions.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/KnownDialogParameters.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/RelativeContentSizeConverter.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/Xaml/DialogLayout.cs
  Source/Xamarin/Prism.Forms/Services/Dialogs/Xaml/ShowDialogExtension.cs
  Source/Xamarin/Prism.Forms/Xaml/Parameter.cs
  Source/Xamarin/Prism.Forms/Xaml/ParameterExtension.cs
  Source/Xamarin/Prism.Forms/Xaml/ParameterExtensions.cs
  Source/Xamarin/Prism.Forms/Xaml/Parameters.cs
  Source/Xamarin/Prism.Forms/Xaml/ParentPageAwareExtension.cs
  Source/Xamarin/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
Labels: XF, enhancement
