Repository PrismLibrary/Prism, pull requests merged in 2020-10, with the labels that each got.

#2207 Fix for Issue 2206 (Register should specify Reuse.Transient explicitly.)
  src/Containers/Prism.DryIoc.Shared/DryIocContainerExtension.cs
  tests/Containers/Prism.Container.DryIoc.Tests/ContainerSetup.cs
  tests/Containers/Prism.Container.DryIoc.Tests/ContainerSetupWithDefaultSingleton.cs
  tests/Containers/Prism.Container.DryIoc.Tests/ContainerTestsWithDefaultSingleton.cs
  tests/Containers/Prism.Container.Shared/Tests/ContainerSetup.cs
Labels: enhancement

#2205 provide xcode override method
  .editorconfig
  build/jobs/uno-uitest.yml
  build/scripts/xcode-update.sh
  build/steps/set-runtime.yml
Labels: housekeeping

#2194 use central package versioning
  .dependabot/config.yml
  Directory.Build.props
  Directory.Build.targets
  Directory.build.targets
  Packages.props
  PrismLibrary.sln
  PrismLibrary_Uno.sln
  build/azure-pipelines.yml
  build/jobs/e2e-uitest.yml
  build/jobs/uno-uitest.yml
  build/steps/build.yml
  e2e/Forms/src/HelloWorld.Android/HelloWorld.Android.csproj
  e2e/Forms/src/HelloWorld.UWP/HelloWorld.UWP.csproj
  e2e/Forms/src/HelloWorld.iOS/HelloWorld.iOS.csproj
  e2e/Forms/tests/HelloWorld.UITests/HelloWorld.UITests.csproj
  e2e/Uno/HelloUnoWorld.Droid/HelloUnoWorld.Droid.csproj
  e2e/Uno/HelloUnoWorld.UITests/HelloUnoWorld.UITests.csproj
  e2e/Uno/HelloUnoWorld.UWP/HelloUnoWorld.UWP.csproj
  e2e/Uno/HelloUnoWorld.Wasm/HelloUnoWorld.Wasm.csproj
  e2e/Uno/HelloUnoWorld.iOS/HelloUnoWorld.iOS.csproj
  e2e/Uno/ModuleA/ModuleA.csproj
  e2e/Wpf/HelloWorld.Bootstraper/HelloWorld.Bootstrapper.csproj
  e2e/Wpf/global.json
  global.json
  src/Directory.Build.props
  src/Forms/Prism.DryIoc.Forms/Prism.DryIoc.Forms.csproj
  src/Forms/Prism.Forms/Prism.Forms.csproj
  src/Forms/Prism.Unity.Forms/Prism.Unity.Forms.csproj
  src/Prism.Core/Prism.Core.csproj
  src/Uno/Prism.DryIoc.Uno/Prism.DryIoc.Uno.csproj
  src/Uno/Prism.Unity.Uno/Prism.Unity.Uno.csproj
  src/Uno/Prism.Uno/Prism.Uno.csproj
  src/Wpf/Prism.DryIoc.Wpf/Prism.DryIoc.Wpf.csproj
  src/Wpf/Prism.Unity.Wpf/Prism.Unity.Wpf.csproj
  src/Wpf/Prism.Wpf/Prism.Wpf.csproj
  tests/Containers/Prism.Container.DryIoc.Tests/Prism.Ioc.DryIoc.Tests.csproj
  tests/Containers/Prism.Container.Unity.Tests/Prism.Ioc.Unity.Tests.csproj
  tests/Forms/Prism.DryIoc.Forms.Tests/Prism.DryIoc.Forms.Tests.csproj
  tests/Forms/Prism.Forms.Tests/Prism.Forms.Tests.csproj
  tests/Forms/Prism.Unity.Forms.Tests/Prism.Unity.Forms.Tests.csproj
  tests/Prism.Core.Tests/Prism.Core.Tests.csproj
  tests/Wpf/Prism.DryIoc.Wpf.Tests/Prism.DryIoc.Wpf.Tests.csproj
  tests/Wpf/Prism.IocContainer.Wpf.Tests.Support/Prism.IocContainer.Wpf.Tests.Support.csproj
  tests/Wpf/Prism.Unity.Wpf.Tests/Prism.Unity.Wpf.Tests.csproj
  tests/Wpf/Prism.Wpf.Tests/Prism.Wpf.Tests.csproj
Labels: housekeeping

#2217 Normalize ViewModelLocator.AutowireViewModel property name for Uno Platform
  e2e/Uno/HelloUnoWorld.Shared/Dialogs/ConfirmationDialog.xaml
  e2e/Uno/HelloUnoWorld.Shared/Dialogs/NotificationDialog.xaml
  e2e/Uno/HelloUnoWorld.Shared/Views/ModulesPage.xaml
  e2e/Uno/HelloUnoWorld.Shared/Views/Shell.xaml
  src/Uno/Prism.Uno/Mvvm/ViewModelLocator.cs
  src/Uno/Prism.Uno/Prism.Uno.csproj
  src/Wpf/Prism.Wpf/Common/MvvmHelpers.cs
Labels: Uno
